# Generated by Django 5.2.5 on 2025-09-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("tracker", "0003_alter_weighttracker_user_alter_workoutplan_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="workout_plans",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to="tracker.workoutplan"
            ),
        ),
    ]
