# Generated by Django 5.2.5 on 2025-09-12 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_workout_plans"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
