# Generated by Django 5.2.5 on 2025-09-27 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_options_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
