# Generated by Django 5.2.5 on 2025-09-02 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("type", models.CharField(max_length=256)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveIntegerField()),
                ("reps", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("weight", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("status", "CUSTOMER"), ("status", "ADMIN"), _connector="OR"
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("version", models.PositiveIntegerField(default=1)),
                ("description", models.TextField()),
                (
                    "creator",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("status", "CUSTOMER"), ("status", "ADMIN"), _connector="OR"
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercises",
                    models.ManyToManyField(
                        related_name="workout_plans",
                        through="tracker.ExerciseSet",
                        to="tracker.exercise",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exerciseset",
            name="workout_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.workoutplan"
            ),
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.workoutplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("status", "CUSTOMER"), ("status", "ADMIN"), _connector="OR"
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="exerciseset",
            unique_together={("exercise", "workout_plan")},
        ),
    ]
