# Generated by Django 5.2.5 on 2025-09-12 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_remove_user_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="weighttracker",
            name="user",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("status", "CUSTOMER"), ("status", "ADMIN"), _connector="OR"),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="creator",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("status", "CUSTOMER"), ("status", "ADMIN"), _connector="OR"),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="user",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("status", "CUSTOMER"), ("status", "ADMIN"), _connector="OR"),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
